title: Android Dagashi
description: Weekly Android developer news digest in Japanese

baseUrl: https://androiddagashi.github.io

issueRepository:
  owner: AndroidDagashi
  name: AndroidDagashi

rssUrl: http://feeds.feedburner.com/AndroidDagashi

contact:
  name: "@AndroidDagashi"
  link: https://twitter.com/AndroidDagashi

authors:
  - name: "@_yshrsmz"
    link: https://twitter.com/_yshrsmz
  - name: "@hydrakecat"
    link: https://twitter.com/hydrakecat
