query getMilestones(
  $repoOwner: String!
  $repoName: String!
  $fetchMilestonesPerPage: Int = 5
  $fetchIssuesPerMilestone: Int = 5
  $fetchCommentsPerIssue: Int = 5
  $fetchLabelsPerIssue: Int = 5
  $endMilestoneCursor: String
) {
  repository(owner: $repoOwner, name: $repoName) {
    name
    description
    milestones(
      first: $fetchMilestonesPerPage
      after: $endMilestoneCursor
      states: [CLOSED]
    ) {
      totalCount
      pageInfo {
        startCursor
        endCursor
        hasPreviousPage
        hasNextPage
      }
      nodes {
        id
        number
        url
        title
        description
        issues(first: $fetchIssuesPerMilestone) {
          totalCount
          pageInfo {
            startCursor
            endCursor
            hasPreviousPage
            hasNextPage
          }
          nodes {
            url
            title
            body
            labels(first: $fetchLabelsPerIssue) {
              nodes {
                name
                description
                color
              }
            }
            comments(first: $fetchCommentsPerIssue) {
              totalCount
              pageInfo {
                startCursor
                endCursor
                hasPreviousPage
                hasNextPage
              }
              nodes {
                body
                author {
                  login
                  url
                  avatarUrl
                }
              }
            }
          }
        }
      }
    }
  }
}
