name: Deploy Website
on:
  workflow_dispatch:
  push:
    branches:
      - development

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy_site:
    name: Deploy Website
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GH_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_USER_NAME: AndroidDagashi
      PROJECT_REPO_NAME: androiddagashi.github.io

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: development

      # run corepack before setup mise
      # https://github.com/actions/setup-node/issues/899
      - run: corepack enable yarn

      - name: Setup mise
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - name: install dependencies
        run: |
          node --version
          corepack enable yarn
          yarn install

      - name: Generate website
        run: yarn workspace site exec nuxi build --preset github_pages

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: master
          folder: ./packages/site/.output/public
          single-commit: true
          git-config-name: 'AndroidDagashi store staff'
          git-config-email: 'androiddagashi-bot@users.noreply.github.com'
