name: Post new release on SNS accounts
on: page_build

jobs:
  update:
    name: Tweet new release
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_SCREEN_NAME: AndroidDagashi
      BLUESKY_IDENTIFIER: androiddagashi.bsky.social
      BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: development

      # run corepack before setup mise
      # https://github.com/actions/setup-node/issues/899
      - run: corepack enable yarn

      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

      - name: install dependencies
        run: |
          node --version
          corepack enable yarn
          yarn install

      - name: setup Firebase
        run: echo ${{ secrets.FIREBASE_JSON }} | base64 -d > ./androiddagashi-serviceaccount.json

      - name: update SNS if not already
        run: yarn sns:update
