name: Post new release on SNS accounts
on: page_build

jobs:
  update:
    name: Tweet new release
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_SCREEN_NAME: AndroidDagashi
      BLUESKY_IDENTIFIER: androiddagashi.bsky.social
      BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: development

      # run corepack before setup-node
      # https://github.com/actions/setup-node/issues/899
      - run: corepack enable yarn

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: setup Firebase
        run: echo ${{ secrets.FIREBASE_JSON }} | base64 -d > ./androiddagashi-serviceaccount.json

      - name: yarn install
        run: yarn install

      - name: update SNS if not already
        run: yarn sns:update
